name: Node.js CI (pnpm)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Move into project directory
        run: cd Loopy-fe && pnpm install

      - name: Build
        run: cd Loopy-fe && pnpm run build

      - name: Test
        run: cd Loopy-fe && pnpm test
