name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd Loopy-fe
          pnpm install

      - name: Build project
        run: |
          cd Loopy-fe
          pnpm run build
