name: Node.js CI (pnpm)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Enable corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        working-directory: Loopy-fe
        run: pnpm install

      - name: Build
        working-directory: Loopy-fe
        run: pnpm run build

      - name: Run tests
        working-directory: Loopy-fe
        run: pnpm test || echo "No tests"
